services:
        db_handler:
                class: AppBundle\Service\DBHandler

        items:
                class: AppBundle\Repository\ItemsRepository
                arguments: ["@db_handler"]

        cart:
                class: AppBundle\Repository\CartRepository
                arguments: ["@db_handler"]

